### ISSUE TITLE
Dashboard examples

### ISSUE THREAD

**Issue by johntdyer** [tanenbaum/raritan-pdu-exporter#1]
Curious if you have an example dashboard for Grafana that makes use of this data source?   If so could you share?

**Comment by tanenbaum** [comment]
I'm not running this currently, but I do know some guys that are. I might not be able to get you configuration, but perhaps a screenshot. Would that help?

**Comment by johntdyer** [comment]
I would love config, I will live w/ a screenshot if I must :) 

-John

**Comment by tanenbaum** [comment]
Unfortunately they're rebuilding the workshop that this is used in at the moment, so there's nothing up and running. 

They did say that it was a very specific dashboard including lots of other unrelated sensors, so probably wouldn't make much sense.

They are using per socket watts, volts, amps and power factor in the dashboards.

Would it be useful if I provided a set of prometheus metrics that one would expect using this exporter?

**Comment by johntdyer** [comment]
Nah, I've got it running for my home lab and I was just being lazy and hoping to leverage someone elses work to build upon for my dashboard.   Thanks anyways
