### ISSUE TITLE
F1125 17:50:31.215366   23660 exporter.go:69] Error getting PDU info: Error performing request: Post "/bulk": unsupported protocol scheme ""

### ISSUE THREAD

**Issue by jcresp21** [tanenbaum/raritan-pdu-exporter#2]
Getting this error when trying the exporter.

Any idea?

**Comment by tanenbaum** [comment]
I think based on that error string that the URL needs a protocol scheme
specifying. So you'll need http://your_pdu or whatever the protocol is.

I'm pretty sure that's coming from Go's `url.Parse` method.

**Comment by jcresp21** [comment]
Thanks Tanen, don't you think the help messages should be changed? 

I've made some changes to Debianize the project and also use config files instead of command line, if you want I can upload the branch.

**Comment by tanenbaum** [comment]
I'm sure there is a lot of work that could be done to make for useful error
messages. I may revisit this project at some point to improve it, but for
now it is what it is.

This is designed primarily to run in a Kubernetes cluster. You could fork
the project to have a deb friendly version of it.
