### ISSUE TITLE
Only getting information with Admin user

### ISSUE THREAD

**Issue by jcresp21** [tanenbaum/raritan-pdu-exporter#3]
Getting an unauthorized error When using a different other than "admin":

The user has been created in the PDU and assigned the Admin role. 

 exporter.go:69] Error getting PDU info: Non 200 status code in RPC response: 401 Unauthorized

**Comment by jcresp21** [comment]
It's because of Radius authentication being turned on. 
And it seems like Ldap/Radius user can't be used to retrieve the data through the plugin. 
For now deactivating remote login or using "admin" with the plugin are the only 2 viable options.

**Comment by tanenbaum** [comment]
This doesn't sound like something I can help you with.
