### ISSUE TITLE
Prometheus not getting the metrics

### ISSUE THREAD

**Issue by jcresp21** [tanenbaum/raritan-pdu-exporter#4]
Hi, I have different raritan exporters running in a k8s environment, I found that the raritan metrics are not being captured by Prometheus, whereas the Golang metrics are.

Could it be because of the "second" value of the Raritan metrics? Is it a timestamp? I find attached an example:
```
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 2.9313808e+07
# HELP go_threads Number of OS threads created.
# TYPE go_threads gauge
go_threads 38   _--> Go metrics are being properly stored in Prometheus._
# HELP pdu_inlet_active_energy inlet sensor reading for activeEnergy
# TYPE pdu_inlet_active_energy gauge
pdu_inlet_active_energy{label="I1",pdu_name="Pdu-en6",pdu_serial_number="XXXXXX"} 0 1331155086000
# HELP pdu_inlet_active_power inlet sensor reading for activePower
# TYPE pdu_inlet_active_power gauge
pdu_inlet_active_power{label="I1",pdu_name="Pdu-en6",pdu_serial_number="XXXXXX"} 0 1331155086000
```

**Comment by tanenbaum** [comment]
Yes, that's the optional timestamp value that is part of the text based
exposition format -
https://prometheus.io/docs/instrumenting/exposition_formats/

The code pulls the time provided by the PDU, since the exporter is scraping
this data from the PDU in the background at a given frequency, not when the
prometheus scrape occurs. I can't remember why we did it this way, but
that's how it works!

**Comment by jcresp21** [comment]
Thanks for the comment,

I modified prom.go , so that it doesn't include the timestamp, I'll have to check why this wasn't working with our Prometheus, as it seems to be a standard option. 

```
//metric <- prometheus.NewMetricWithTimestamp(l.Time,
//	prometheus.MustNewConstMetric(
metric <- prometheus.MustNewConstMetric(
prometheus.NewDesc(
	prometheus.BuildFQName(namespace, strings.ToLower(l.Type), c.metricNames(l.Sensor)),
	fmt.Sprintf("%s sensor reading for %s", l.Type, l.Sensor), []string{"label"}, labels),
prometheus.GaugeValue, l.Value, l.Label)
````

**Comment by tanenbaum** [comment]
That'll do the trick.

Looks like that timestamp is quite a few years in the past. Did you convert
the time and search in that range?
