### ISSUE TITLE
feature request: add OverCurrentProtector in export

### ISSUE THREAD

**Issue by sanderdescamps** [tanenbaum/raritan-pdu-exporter#5]
Currently the exporter does not export the metrics of the over current protector. I believe this is valuable information so it would be nice if it could be added. 

I've implemented the feature already and will soon create a merge request to have it merged.

**Comment by tanenbaum** [comment]
Hey @sanderdescamps I've merged the PR, but I can't actually test it. Let me know if everything is working as expected!

**Comment by sanderdescamps** [comment]
According to the tests I did, it is working.
