### ISSUE TITLE
Feature Request: export on multiple pdu's

### ISSUE THREAD

**Issue by sanderdescamps** [tanenbaum/raritan-pdu-exporter#7]
In our environment we have a large amount of pdu's where we want to export the metrics to Prometheus. Now with the current exporter, I need to deploy a service for every pdu. This works when you have a couple pdu's, but in our case this isn't ideal anymore.

I would like to add a feature which allows the exporter to report on a pool of pdu's. Then via the path (or params) the proper pdu would be selected from the pool. 

Normally I will be able to get the resources to implement this feature. I mainly want to know if the maintainers of this repo are open to accept such a change? I will do my best to make everything 100% backwards compatible but I'm not sure yet if that will be possible.

**Comment by tanenbaum** [comment]
Yes, please do go ahead.

We only ever had one PDU to work with anyway, but I can see how this will become difficult when scaling up.
